// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dmocpbybwdgxzpprsyji.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRtb2NwYnlid2RneHpwcHJzeWppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0NTQ2NTksImV4cCI6MjA2MzAzMDY1OX0.OJ5W1S5R4MY9mZkVCwpX33aiL2zhaogI6aQw2rgtt9k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);